<?

$prev = $big_picture_day_offset - 1;
$next = $big_picture_day_offset + 1;
?>

<div id="big-picture" class="cell">
    <div class="grid-x align-middle">
        <div class="small-1 cell text-center">
            <a class="special-button" title="see total for previous day"
               hx-trigger="click, keyup[shiftKey&&key=='A'] from:body"
               hx-get='<?=Flight::url()->sign("/home/big-picture/rel/{$prev}")?>'
               hx-swap="outerHTML swap:200ms"
               hx-target='#big-picture'><i class="gg-arrow-left-r"></i></a>
        </div>
        <div id="big-picture--section-2" class="small-10 cell custom-shadow" data-classes="">
            <div class="text-center">
                <div id="today-total" class="text-center"><p class='margin-0'><span><?=number_format($today_points, 2)?></span><sup class="super"><u>PTS</u></sup></p></div>
            </div>
        </div>
        <div class="small-1 cell text-center">
            <a class="special-button" title="see total for next day"
               hx-trigger="click, keyup[shiftKey&&key=='D'] from:body"
               hx-get="<?=Flight::url()->sign("/home/big-picture/rel/{$next}")?>"
               hx-swap="outerHTML swap:200ms"
               hx-target='#big-picture'><i class="gg-arrow-right-r"></i></a>
        </div>
        <div class="cell small-offset-1">
            <p class="text-left subheader"><?=$title?></p>
        </div>


    </div>
</div>
<div id="big-picture--section-3" class="cell auto">
    <form action="" name="day-info">
        <fieldset class="cell small-12 fieldset">
            <legend>exercise info</legend>
            <input name="exercised"
                   type="checkbox"
                   hx-post='<?=Flight::url()->sign("/journal-entry/exercised/rel/{$big_picture_day_offset}")?>'
                   hx-target="#exercised-statement"
                   <?=(1 == $exercised_bpo) ? "checked":""?>
            />
            <label for="exercised">Did you exercise today?</label>
            <br>
            <?=Flight::render("partials/exercised-statement", [])?>
        </fieldset>
    </form>
</div>
<div id="big-picture--footer" class="cell auto">
    <div id="statistics" class="callout">
        <p>
            You are averaging <strong><?=number_format($stats->avgDaily(), 2)?></strong> points per logged-day.
        </p>
        <p>
            Trailing 7-day average: <strong><?=number_format($stats->avgDailyTrailing7(), 2)?></strong> points per logged-day
        </p>
    </div>
</div>
<script type="text/javascript">
 if ("undefined" != typeof $) {
     $(function() {
         qs.set({
             bpo: '<?=$big_picture_day_offset?>',
         });
     });
 }
</script>
