<?
$prev = $big_picture_day_offset - 1;
$next = $big_picture_day_offset + 1;
?>
<div id="big-picture" class="card custom-shadow">
    <div class="card-divider button-group align-justify">
        <a class="button" title="see total for previous day"
           hx-trigger="click, keyup[shiftKey&&key=='A'] from:body"
           hx-get='<?=Flight::url()->sign("/home/big-picture/rel/{$prev}")?>'
           hx-swap="outerHTML swap:200ms"
           hx-target='#big-picture'><i class="gg-arrow-left-r"></i></a>
        <h4><a title="see total for today"
               hx-trigger="click, path-deps, keyup[shiftKey&&key=='S'] from:body"
               path-deps="/journal-entry"
               hx-get="<?=Flight::url()->sign("/home/big-picture/rel/0")?>"
               hx-swap="outerHTML swap:200ms"
               hx-target='#big-picture'><?=$title?></a></h4>
        <a class="button" title="see total for next day"
           hx-trigger="click, keyup[shiftKey&&key=='D'] from:body"
           hx-get="<?=Flight::url()->sign("/home/big-picture/rel/{$next}")?>"
           hx-swap="outerHTML swap:200ms"
           hx-target='#big-picture'><i class="gg-arrow-right-r"></i></a>
    </div>
    <div class="card-section">
        <div class="callout secondary text-center">
            <div id="today-total" style="font-size:5rem"><?=number_format($today_points, 2)?> points</div>
        </div>
    </div>
    <div class="card-section">
        <form action="" name="day-info">
            <fieldset class="cell small-12 fieldset">
                <input name="exercised"
                       type="checkbox"
                       hx-post='<?=Flight::url()->sign("/exercised/rel/{$big_picture_day_offset}")?>'
                       hx-target="#exercised-statement"
                       <?=(1 == $exercised_bpo) ? "checked":""?>
                />
                <label for="exercised">Did you exercise today?</label>
                <br>
                <?=Flight::render("partials/exercised-statement", [])?>
            </fieldset>
        </form>
    </div>
    <div class="card-footer">
        <div class="cell auto">
            <div id="statistics" class="callout">
                <p>
                    You are averaging <strong><?=number_format($stats->avgDaily(), 2)?></strong> points per logged-day.
                </p>
                <p>
                    Trailing 7-day average: <strong><?=number_format($stats->avgDailyTrailing7(), 2)?></strong> points per logged-day
                </p>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
 if ("undefined" != typeof $) {
     $(function() {
         qs.set({
             bpo: '<?=$big_picture_day_offset?>'
         });
     });
 }
</script>
