<table id="journal-table" class="hover" data-order='[[ 0, "desc" ]]'>
    <thead>
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Food</th>
            <th scope="col">Multiplier</th>
            <th scope="col">Points</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody hx-target="closest tr" hx-swap="outerHTML swap:1s">
        <? if (empty($records)) { ?>
            <tr class="empty-row-notice">
                <td class="text-center" colspan="100%"><em>Your food log is empty.</em></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        <? } ?>
        <? foreach ($records as $record) { ?>
            <tr data-id='<?=$record['id']?>'>
                <?
                $_date = $record['date'];
                if (false == strtotime($_date)) {
                    $date = "?";
                } else {
                    $date = date_create($_date)->format("m/d/Y");
                }
                ?>
                <td id="date-<?=$record['id']?>" data-rowid='<?=$record['id']?>' data-sort="<?=strtotime($_date)?>" data-name='date' contenteditable="true"><?=$date?></td>
                <td id="food-<?=$record['id']?>" data-rowid='<?=$record['id']?>' data-name='food'><?=Flight::getFood($record['food'])?></td>
                <td id="quantity-<?=$record['id']?>" class="text-right" data-rowid='<?=$record['id']?>' data-name='quantity' contenteditable="true"><?=$record['quantity']?></td>
                <td id="points-<?=$record['id']?>" class="text-right" data-rowid='<?=$record['id']?>' data-name='points'><?=number_format($record['points'], 2)?></td>
                <td>
                    <div class="button-group stacked" role="group">
                        <button type="button" class="alert button" data-rowid='<?=$record['id']?>' disabled name='save-row-button' style="cursor:not-allowed;opacity:0.25;">save</button>
                        <button type="button" class="button"
                                hx-swap="#message"
                                hx-delete="/journal-entry/<?=$record['id']?>">
                            delete
                        </button>
                    </div>
                </td>
            </tr>
        <? } ?>
    </tbody>
</table>
