<div id='this-container2' class="calendar grid-x">
    <div class="cell small-1">
        lol
    </div>

    <div class="cell small-1">
        lol
    </div>
    <div class="cell small-1">
        lol
    </div>
    <div class="cell small-1">
        lol
    </div>
    <div class="cell small-1">
        lol
    </div>

    <!-- <div class="cell small-1">
         <div class="card">
         <div class="card-divider">
         31st
         </div>
         <div class="card-section">
         19 points
         </div>
         </div>
         </div>
         <div class="cell small-1">
         <div class="card">
         <div class="card-divider">
         31st
         </div>
         <div class="card-section">
         19 points
         </div>
         </div>
         </div>
         <div class="cell small-1">
         <div class="card">
         <div class="card-divider">
         31st
         </div>
         <div class="card-section">
         19 points
         </div>
         </div>
         </div>
    -->
</div>
