<?
use Carbon\Carbon;

if (empty($journal_day_offset)) {
    $journal_view_date = Flight::now("D M j, Y");
    $journal_date = date("Y-m-d");
    $colloqial_date = "&nbsp";
} else {
    $journal_view_date = date_create()->add(date_interval_create_from_date_string ("{$journal_day_offset} days"))->format("D M j, Y");
    $journal_date = date_create()->add(date_interval_create_from_date_string ("{$journal_day_offset} days"))->format("Y-m-d 00:00:00");

    switch(strtotime($journal_date)) {
        case (strtotime("yesterday")):
            $colloqial_date = "yesterday";
            break;
        case (date("Y-m-d")):
            $colloqial_date = "today";
            break;
        default:
            $colloqial_date = "&nbsp;";
            break;
    }
}


$stats = Flight::stats();

$records = $stats->journalEntries($journal_day_offset);

$today_points = $stats->points($journal_day_offset);

$exercised = $stats->exercised($journal_day_offset);

?>
<style>
 .fade-me-out.htmx-swapping {
     opacity: 0;
     transition: opacity 1s ease-out;
 }
</style>
<!-- Your menu or Off-canvas content goes here -->
<div id='this-container' class="grid-y">
    <div class="cell">
        <div class="button-group align-spaced align-middle">
            <a class="button" title="see entry for yesterday"
               hx-indicator="#indicator"
               hx-get="/journal/rel/<?=($journal_day_offset - 1)?>"
               hx-swap="outerHTML"
               hx-target='#this-container'>⬅</a>
            <a hx-get="/journal/rel/<?=($journal_day_offset)?>"
               hx-swap="outerHTML"
               path-deps="/submit-food-log"
               hx-trigger="click, path-deps"
               hx-target='#this-container'><h1 style='margin:0'><?=$journal_view_date?></h1></a>
            <a class="button fade-me-out" title="see entry for tomorrow"
               hx-get="/journal/rel/<?=($journal_day_offset + 1)?>"
               hx-swap="outerHTML"
               hx-target='#this-container'>⮕</a>
        </div>
    </div>
    <div class="cell">
        <div class="callout">
            <strong>Consumed: <?=$today_points?> points</strong>
            <br>
            <strong>Exercised this day: <?=$exercised ? "YES!": "NOPE"?></strong>
        </div>
    </div>
    <div class="cell">
        <div class='callout'>
            <div class="table-scroll">
                <?=Flight::render("partials/journal", [
                    "records" => \Flight::journalItem()->whereDate("date", "=", Carbon::now()->addDays($journal_day_offset))->get(),
                    "offset" => $journal_day_offset,
                ])?>
            </div>
        </div>
    </div>
</div>
