---
image: php:7.4

stages:
  - test

php:
  stage: test
  script:
    - composer install
    - './vendor/bin/phpcs -s -p --colors --extensions=php .'

on-pull-requests:
  script: echo 'this should run on pull requests'
  only:
    - external_pull_requests
