---
image: php:7.4

stages:
  - test

before_script:
  - php -m
  - bash ci/docker_install.sh > /dev/null

php:
  stage: test
  cache:
    paths:
      - vendor
  script:
    - composer install
    - './vendor/bin/phpcs -s -p --colors --extensions=php .'
    - './vendor/bin/phpmd ./src/app/ ansi ./phpmd.xml'

on-pull-requests:
  script: echo 'this should run on pull requests'
  only:
    - external_pull_requests
