---

version: '3.8'
services:
  web:
    profiles:
      - backend
    container_name: ${COMPOSE_PROJECT_NAME}.web
    image: ${NGINX_IMAGE}
    ports:
      - '9090:80'
    volumes:
      - ./:/var/www
      - ./wtw.paxperscientiam.com/:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm

  php-fpm:
    profiles:
      - backend
    container_name: ${COMPOSE_PROJECT_NAME}.php
    image: ${PHP_IMAGE}
    expose:
      - 9000
    volumes:
      - ./:/var/www
      - ./wtw.paxperscientiam.com/:/var/www/html
    # build:
    #   context: ./
    #   args:
    #     PHP_IMAGE: ${PHP_IMAGE}


#     # env_file:
#     #   - ./docker/.env
#     volumes:
#       - ./:/var/www/
#        # - ./wtw.paxperscientiam.com:/var/www/files/wtw.paxperscientiam.com
#        # - /var/www/files/storage/ # cache and sqlite database
#        # - ./package.json:/var/www/files/package.json
#        # - ./composer.json:/var/www/files/composer.json
#        # - node_modules:/var/www/files/node_modules
#        # - vendor:/var/www/files/vendor       
#     ports:
#       - 9005:80

#   # npm-update:
#   #   command: node index.js
#   #   depends_on:
#   #     - php-apache-environment


# # volumes:
# #   wtw:
# #   vendor:
# #   node_modules:
# #   logs:
