version: '3.8'
services:
  php-apache-environment: &base
    container_name: php-apache
    build:
      context: ./
      args:
        PHP_IMAGE: ${PHP_IMAGE}
    env_file:
      - ./docker/.env
    volumes:
       - ./app:/var/www/files/app
       - ./wtw.paxperscientiam.com:/var/www/files/wtw.paxperscientiam.com
       - /var/www/files/storage/appcache
       - /var/www/files/storage/db
       - ./bootstrap:/var/www/files/bootstrap
       - ./config:/var/www/files/config
       - ./views:/var/www/files/views
       - ./package.json:/var/www/files/package.json
       - ./composer.json:/var/www/files/composer.json
       - node_modules:/var/www/files/node_modules
       - vendor:/var/www/files/vendor
    ports:
      - 9005:80

  # npm-update:
  #   command: node index.js
  #   depends_on:
  #     - php-apache-environment


volumes:
  wtw:
  vendor:
  node_modules:
  logs:
