version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./
      args:
        PHP_IMAGE: ${PHP_IMAGE}
        NODE_IMAGE: ${NODE_IMAGE}
    env_file:
      - ./docker/.env
    volumes:
       - wtw:/etc/db
       - ./wtw.paxperscientiam.com:/var/www/files/wtw.paxperscientiam.com
       - ./app::/var/www/files/app
    ports:
      - 9000:80
  # composer_installation:
  #   container_name: composer_installation
  #   image: composer:2.1.6
  #   command: ["composer", "install"]
  #   volumes:
  #     - wtw:/var/www/files/

volumes:
  wtw:
  vendor-files:
  node_modules-files:
