version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./
      args:
        PHP_IMAGE: ${PHP_IMAGE}
        NODE_IMAGE: ${NODE_IMAGE}
    env_file:
      - ./docker/.env
    volumes:
       - wtw:/etc/db # persisted volume data
       - node_modules:/var/www/files/node_modules
       - vendor:/var/www/files/vendor
       - ./wtw.paxperscientiam.com:/var/www/files/wtw.paxperscientiam.com
       # - ./app:/var/www/files/app
       # - ./bootstrap:/var/www/files/bootstrap
       # - ./config:/var/www/files/config
       # - ./views:/var/www/files/views
    ports:
      - 9000:80
  # composer_installation:
  #   container_name: composer_installation
  #   image: composer:2.1.6
  #   command: ["composer", "install"]
  #   volumes:
  #     - wtw:/var/www/files/

volumes:
  wtw:
  vendor:
  node_modules:
