version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./docker/php
      args:
        PHP_IMAGE: ${PHP_IMAGE}
    env_file:
      - ./docker/php/.env
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/app.ini
      - ./:/var/www/files/
      - ./docker/php/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/my-vhosts.conf:/etc/apache2/conf-available/my-vhosts.conf

    ports:
      - 9000:80
