version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./
      args:
        PHP_IMAGE: ${PHP_IMAGE}
        NODE_IMAGE: ${NODE_IMAGE}
    env_file:
      - ./docker/.env
    volumes:
       - ./:/var/www/files
       - wtw:/var/www/files/storage/appcache # persist cache
       - wtw:/var/www/files/storage/db # persist db
       - logs:/var/www/logs # persis logs
       - node_modules:/var/www/files/node_modules # persisted node
       - vendor:/var/www/files/vendor # persisted vendor
       # - ./app:/var/www/files/app
       # - ./bootstrap:/var/www/files/bootstrap
       # - ./config:/var/www/files/config
       # - ./views:/var/www/files/views
    ports:
      - 9000:80
  # composer_installation:
  #   container_name: composer_installation
  #   image: composer:2.1.6
  #   command: ["composer", "install"]
  #   volumes:
  #     - wtw:/var/www/files/

volumes:
  wtw:
  vendor:
  node_modules:
  logs:
