version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./docker/backend
      args:
        PHP_IMAGE: ${PHP_IMAGE}
    env_file:
      - ./docker/backend/.env
    volumes:
      - wtw-db:/etc/db
      - ./docker/backend/php.ini:/usr/local/etc/php/conf.d/app.ini
      - ./docker/backend/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/backend/my-vhosts.conf:/etc/apache2/conf-available/my-vhosts.conf
      - ./:/var/www/files/
    ports:
      - 9000:80
    depends_on:
      - composer_installation

  composer_installation:
    container_name: composer_installation
    image: composer:2.1.6
    command: ["composer", "install"]
    volumes:
      - ./backend/:/app
volumes:
  wtw-db:
  vendor-files:
  node_modules-files:
