<?
use Carbon\Carbon,
Tracy\Debugger;
?>
<!-- mode: web -->
<!doctype html>
<html lang="en">
    <?php Debugger::renderLoader() ?>
    <head>
        <meta charset="UTF-8"/>
        <title>Worth the Weight!</title>
        <?=Flight::render("generated/resources", [])?>
        <link rel="icon" href="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%2016%2016'%3E%3Ctext%20x='0'%20y='14'%3E🦄%3C/text%3E%3C/svg%3E" type="image/svg+xml" />
    </head>
    <body hx-ext="path-deps">
        <? foreach ($records as $record) { ?>
            <?=$record->id?>
        <? } ?>
        <? if (true === Flight::get("debug_mode")) { ?>
            <button type="button"
                    onclick="delayedReload(500)"
                    class="button alert"
                    style="position:fixed;left:0;bottom:0"
                    name='drop-food-records'
                    hx-swap='none'
                    hx-post="/drop-food-log">
                DELETE ENTIRE FOOD LOG</button>
        <? } ?>
        <div class="title-bar">
            <div class="title-bar-left">
                <button class="menu-icon" type="button" data-toggle="offCanvas"></button>
                <span class="title-bar-title">View journal</span>
                <span><button class="small button" hx-swap='none' hx-post="/logout">log out</button></span>
            </div>
            <div class='text-center'
                 hx-get='/food-support-message'
                 hx-trigger="path-deps"
                 hx-swap='innerHTML'
                 path-deps="/journal-entry"><?=Flight::welcome()?>, <?=Flight::auth()->getUsername()?></div>
            <div class="title-bar-right">
                <span><?=" The date is " . Carbon::now()->format("D M j, Y")?></span>
            </div>
            <div class="title-bar-right">
                <span class="title-bar-title">View graphs</span>
                <button class="menu-icon" type="button" data-toggle="offCanvas2"></button>
            </div>
        </div>

        <div class="off-canvas-wrapper">
            <div class="off-canvas position-left off-canvas-absolute" id="offCanvas" data-off-canvas
                 hx-get="/home/left-canvas/rel/<?=Flight::get('omo')?>"
                 hx-trigger="path-deps"
                 path-deps="/journal-entry">
                <?=Flight::render("partials/offcanvas-menu", [
                ])?>
            </div>

            <div class="off-canvas position-right off-canvas-absolute" id="offCanvas2" data-off-canvas>
                <?=Flight::render("partials/offcanvas-graphs", [
                ])?>
            </div>
            <div class="off-canvas-content" data-off-canvas-content>
                <div class="grid-container">

                    <div class="grid-x grid-margin-x align-middle">
                        <div class="cell small-12 large-4">
                            <form name='food-log-form' class="grid-x" onsubmit="this.reset()">
                                <fieldset class="cell small-12 fieldset">
                                    <legend>food info</legend>
                                    <div class='form-group'>
                                        <label><strong>Select date</strong></label>
                                        <input class="form-control" name="date" type="date" value="<?=Carbon::now()->format("Y-m-d")?>" required/>
                                    </div>
                                    <div class="form-group">
                                        <label><strong>Select food:</strong></label>
                                        <select id="food-selection" name='food-selection' class='form-control' required>
                                            <option value="" selected>Select food ...</option>
                                            <? foreach ($foods as $food) { ?>
                                                <option value="<?=$food->id?>"><?=$food->food_name?> (<?=$food->points?> points)</option>
                                            <? } ?>
                                        </select>
                                    </div>
                                </fieldset>
                                <fieldset class="cell small-12 fieldset">
                                    <div class="form-group">
                                        <label><strong>Multiplier <small>(fraction of food selection base quantity)</small></strong></label>
                                        <input class='form-control' type="text" name="amount" value="" data-inputmask="'alias': 'numeric'" required />
                                    </div>
                                </fieldset>
                                <button type="submit" class="button success large"
                                        hx-post="/journal-entry"
                                        hx-swap="none">submit</button>
                            </form>
                        </div>

                        <div class="cell small-12 large-8">
                            <div class="grid-x grid-margin-x align-center-middle">
                                <?Flight::render("partials/big-picture", [])?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <script>

         htmx.onLoad(function(elt){
             if ("this-container2" == elt.id) {
                 initCalendar()
             }
         });
        </script>
    </body>
</html>
