<?PHP
use Carbon\Carbon,
Tracy\Debugger,
Illuminate\Support\Facades\Config;


?>
<html lang="en" class="no-js">
    <?php Debugger::renderLoader() ?>
    <head>
        <meta charset="UTF-8"/>
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Worth the Weight!</title>
        <?=Flight::render(Config::get('app.web_root') . "/dist/resources", [])?>
        <link rel="icon" href="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20viewBox='0%200%2016%2016'%3E%3Ctext%20x='0'%20y='14'%3E🦄%3C/text%3E%3C/svg%3E" type="image/svg+xml" />
    </head>
    <body>

        <form class="grid-x">
            <fieldset class="cell small-12 fieldset">
                <legend>food info</legend>
                <div class='form-group'>
                    <label><strong>Date (required)</strong></label>
                    <input class="form-control" name="date" type="date" value="<?=Carbon::now()->format("Y-m-d")?>" required/>
                </div>
                <div class="form-group">
                    <label for=""><strong>Nuber</strong></label>
                    <input class="form-control" name="this-you-man" type="text" value="" hx-post="/form-test/this-you-man"/>
                </div>
            </fieldset>
            <div class="cell small-12">
                <button type="submit"
                        class="large button expanded"
                        hx-post="/form-test"
                        hx-swap='none'>save</button>
            </div>
        </form>

    </body>

</html>
