<?PHP

s(App\Enums\PlanSelection::GREEN);



s(gethostname());


exit;

foreach ($plans::get() as $plan) {
    s($plan->hasOneThrough(
        App\Models\User::class,
        App\Models\UserSettings::class,
        'plan_id', // Foreign key on the user_settings table...
        'id', // Foreign key on the user table...
        'id', // Local key on the plans table...
        'user_id' // Local key on the user_settings table...
    )->toSql());
}

/* $food_model = new App\Models\Food();
 * 
 * s($user->today->toArray());;
 * 
 * s($user->currentDailyPointsGoal->toArray());
 * 
 * 
 * s($food_model->first()->green_plan_points); */
