<div class="reveal" id="user-settings-modal" data-reveal>
    <h1>Settings</h1>
    <form name='user-settings-form'
          class='grid-x'
          data-abide novalidate>
        <fieldset class="cell small-12 fieldset">
            <legend>Plan</legend>
            <div class="form-group">
                <label><strong>select plan</strong></label>
                <select id="plan-selection" name='plan-selection' class='form-control' required>
                    <option data-placeholder="true"></option>
                    <? foreach ((new \App\Models\Plans())::get() as $plan) { ?>
                        <? if (Flight::get('ActiveUser')->settings->plan->id == $plan->id) { ?>
                            <option value="<?=$plan->id?>" selected><?=$plan->plan_short_name?></option>
                        <? } else { ?>
                            <option value="<?=$plan->id?>"><?=$plan->plan_short_name?></option>
                        <? } ?>
                    <? } ?>
                </select>
            </div>
            <div class="form-group">
                <label for=""><strong>points goal</strong></label>
                <input id="plan-points-goal" class="form-control" name="plan-points-goal" type="text" value="" data-inputmask="'alias': 'numeric'" pattern="number"/>
                <span id="error" class='form-error'></span>
            </div>
        </fieldset>
        <div class="cell small-12">
            <button type="submit"
                    class="large button expanded"
                    hx-post="/user-settings/"
                    hx-swap='none'>save</button>
        </div>
    </form>

    <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

