<?
use Carbon\Carbon;
?>
<div class="reveal medium" id="user-settings-modal" data-reveal>
    <h1>Vitals</h1>
    <form name='user-settings-form'
          hx-post="/user-vitals/weight"
          hx-swap='none'
          class='grid-x'>
        <fieldset class="cell small-12 fieldset">
            <legend>Weight</legend>
            <div class="form-group">
                <label><strong>Select log date</strong></label>
                <input class="form-control" name="weight_log[date]" type="date" value="<?=Carbon::now()->format("Y-m-d")?>" required/>
                <p class="help-text">Only change if entering your weight for a past date.</p>
            </div>
            <div class="grid-x input-group">
                <label><strong>Weight</strong></label>
                <div class="input-group">
                    <input class='input-group-field' type="text" name="weight_log[amount]" value="" data-inputmask="'alias': 'numeric'"/>
                    <span class="input-group-label"><?=$settings->weight_unit->unit_name?></span>
                    <div class="input-group-button">
                        <input type="submit" class="button" value="Submit">
                    </div>
                </div>
                <p class="help-text">To change how weight is measured (pounds or kilos), edit your settings.</p>
            </div>
        </fieldset>
    </form>

    <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
