<div class="reveal" id="exampleModal1" data-reveal>
    <p>Jump to <strong><?=$displayDate?></strong> in your journal?</p>
    <div class="button-group">
        <a class="success button" data-accept>OK</a>
        <a class="secondary button" data-close>Cancel</a>
    </div>
    <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
