<div class="tiny reveal" id="delete-journal-item-modal" data-reveal data-close-on-click='true'>
    Are you sure you want to delete this journal entry?
    <button type="button" class="button"
            hx-swap="#message"
            hx-trigger="click"
            hx-delete="/journal-entry/<?=$id?>">
        Yes
    </button>
    <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

