<div class="reveal" id="add-food-item-modal" data-reveal>
    <h1>Add a custom food item</h1>

    <form class="grid-x" name="add-food-item">
        <fieldset class="cell small-12 fieldset">
            <legend>description</legend>
            <div class="form-group">
                <label for=""><strong>food name</strong></label>
                <input id="new-food-name" class="form-control" name="new-food-name" type="text" value=""/>
            </div>
            <div class="form-group">
                <label for=""><strong>points</strong></label>
                <input id="new-food-points" class="form-control" name="new-food-points" type="text" value="" data-inputmask="'alias': 'numeric'" pattern="number"/>
            </div>

            <div class="form-group">
                <label><strong>select plan</strong></label>
                <select id="plan-selection" name='plan-selection' class='form-control' required>
                    <option data-placeholder="true"></option>
                    <? foreach ((new \App\Models\Plans())::get() as $plan) { ?>
                        <? if ($app->get('ActiveUser')->settings->plan->id == $plan->id) { ?>
                            <option value="<?=$plan->id?>" selected><?=$plan->plan_short_name?></option>
                        <? } else { ?>
                            <option value="<?=$plan->id?>"><?=$plan->plan_short_name?></option>
                        <? } ?>
                    <? } ?>
                </select>
            </div>
        </fieldset>

        <div class="cell small-12">
            <button type="submit"
                    class="large button expanded"
                    hx-post="/user-custom-food/"
                    hx-swap='none'>save new food</button>
        </div>
    </form>


    <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
</div>
