<div class="tiny reveal" id="delete-journal-item-modal" data-reveal data-close-on-click='true'>
    <p>Are you sure you want to delete this journal entry?</p>
    <div class="button-group">
        <a class="success button" hx-swap="none" hx-delete="/journal-entry/77">OK</a>
        <a class="secondary button" data-close>Cancel</a>
    </div>
    <button class="close-button" data-close aria-label="Close modal" type="button">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

